### ISSUE TITLE
Notifications overlapped (z-index of notifications__container fixed to 1000)

### ISSUE THREAD

**Issue by CicheR** [jossmac/react-toast-notifications#121]
Issue: 
![image](https://user-images.githubusercontent.com/46723276/87008207-8d9fba80-c202-11ea-97db-7a259fd0c1f1.png)

In my case I solved it by simply overriding the `react-toast-notifications__container` class:
```css
.react-toast-notifications__container {
  z-index: 1100 !important;
  top: 64px !important;
}
```

---

Would it be useful to have the possibility to customize the `z-index`? (It could be in a ToastProvider property, for example).
If so, I could make the change and generate a pull request. 
I would like to be able to collaborate with the project. 🤗
